on: [push]

name: Test

jobs:
  Tarpaulin:
    name: Test and export coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Ebook-Convert
        id: cache-ebook-convert
        uses: actions/cache@v3
        with:
          path: ebook-convert
          key: ${{ runner.os }}-calibre

      - name: Install Ebook-Convert
        if: steps.cache-ebook-convert.outputs.cache-hit != 'true'
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin && cp /usr/bin/ebook-convert .

      - name: Install Ebook-Convert (from cache)
        if: steps.cache-ebook-convert.outputs.cache-hit == 'true'
        run: sudo mv ebook-convert /usr/bin/ebook-convert

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.0'
          args: '--exclude-files src/main.rs -- --show-output --include-ignored' # Run the ignored tests as well

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
