on: [push]

name: Test

jobs:
  Tarpaulin:
    name: Test and export coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ebook-Convert
        # if: steps.cache-ebook-convert.outputs.cache-hit != 'true'
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          CARGO_INCREMENTAL: 1
        with:
          version: '0.20.0'
          args: '--skip-clean --exclude-files src/main.rs -- --show-output --include-ignored' # Run the ignored tests as well

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
